all: day01 day02 day03

# COMPILATION PROCESS
day01:
	g++ day01.cpp -o day01.out

day02:
	g++ day02.cpp -o day02.out

day03:
	g++ day03.cpp -o day03.out

day04:
	g++ day04.cpp -o day04.out

# CLEAR BUILDS
clean:
	rm *.out